{% set version = "1300.6.5" %}

package:
  name: tapi
  version: {{ version }}

source:
  # latest commit from branch called `{{ version }}`
  - url: https://github.com/tpoechtrager/apple-libtapi/archive/b8c5ac40267aa5f6004dd38cc2b2cd84f2d9d555.tar.gz
    sha256: 3b75098ee01571102e605c76b219075c607df0dd459e65fc04cb282fbe7c65cb

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    # C-compiler only for bin/x86_64-conda-linux-gnu-cc symlink;
    # cannot add this on osx because of circular dependence
    - {{ compiler('c') }}   # [linux]
    - ncurses               # [osx and arm64]
    - cmake
    - ninja
  host:
    - libcxx                # [osx]
    - ncurses               # [osx]
{% if cxx_compiler_version is defined %}
  run:
    - libcxx >={{ cxx_compiler_version }}.0.0.a0  # [osx]
{% endif %}

test:
  commands:
    - test -f $PREFIX/lib/libtapi${SHLIB_EXT}
    - test -f $PREFIX/include/tapi/tapi.h

about:
  home: https://opensource.apple.com/source/tapi
  license: NCSA
  license_family: MIT
  license_file:
    - LICENSE.APPLE-LIBTAPI.txt
    - LICENSE.LLVM.txt
  summary: 'TAPI is a Text-based Application Programming Interface'
  doc_url: https://opensource.apple.com/source/tapi/tapi-{{ version }}/Readme.md
  dev_url: https://github.com/ributzka/tapi

extra:
  recipe-maintainers:
    - isuruf
